name: fruits_market
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  injectable: ^2.5.1
  get_it: ^8.0.3
  flutter_native_splash: ^2.4.6
  phone_numbers_parser: ^9.0.3
  flutter_otp_text_field: ^1.5.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.8.0
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.13.1

flutter_assets:
  assets_path: assets/images/
  output_path: lib/assets
  filename: assets.dart
  field_prefix:


flutter:


  uses-material-design: true

 
  assets:
    - assets/images/svg/
    - assets/images/png/


  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
          
flutter_native_splash:
  color: "#003500"
  image: assets/images/png/logo.png

  android_12:
    image: assets/images/png/logo.png
    color: "#003500"

  # color_dark: "#000000"
  # image_dark: assets/images/png/logo_dark.png

  android: true
  ios: true
  web: true


  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/png/logo.png
  adaptive_icon_background: "#003500"
  adaptive_icon_foreground: assets/images/png/logo.png
  adaptive_icon_foreground_inset: 25