name: fruits_market
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  injectable: ^2.5.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.8.0
  build_runner: ^2.6.0

flutter_assets:
  assets_path: assets/images/
  output_path: lib/assets
  filename: assets.dart
  field_prefix:


flutter:


  uses-material-design: true

 
  assets:
    - assets/images/svg/
    - assets/images/png/


  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
          
